### ISSUE TITLE
GET /search with 'collections' parameter always returns 0 results

### ISSUE THREAD

**Issue by philvarner** [nasa/cmr-stac#169] opened 2021-05-28 14:14 UTC
Expected:

These two requests should return identical results.

OAFeat:
```
https://cmr.earthdata.nasa.gov/stac/LARC_ASDC/collections/NIMBUS7_ERB_SEFDT.v1/items
```

STAC API Item Search:
```
https://cmr.earthdata.nasa.gov/stac/LARC_ASDC/search?collections=NIMBUS7_ERB_SEFDT.v1
```

Actual:

The Item Search GET query returns 0 results. 

Note that this does work correctly with POST:

```
curl -X "POST" "https://cmr.earthdata.nasa.gov/stac/LARC_ASDC/search" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "collections": [
    "NIMBUS7_ERB_SEFDT.v1"
  ]
}'
```

**Comment by matthewhanson** [comment] 2021-06-02 01:46
This is a known issue and I thought there was an issue for it already but it must be an internal CMR one.

The problem is that for GET requests, parameters that have multiple values are not being forwarded to the Lambda function, and appears to possibly be an issue with the way CMR-STAC is deployed behind a Load Balancer rather than API Gateway.

So when you provide the collections parameter it's actually treating it as an array (like it expects with POST), so you end up with an array of 1-letter collections that don't exist.

You can force it to understand that the entire string is an element of the array with this:
https://cmr.earthdata.nasa.gov/stac/LARC_ASDC/search?collections[]=NIMBUS7_ERB_SEFDT.v1

We hope to get this fixed in the coming weeks.

**Comment by matthewhanson** [comment] 2021-06-02 01:48
Note this also means that if you supply an array of collection IDs (or Item IDs, or a bbox array) that it will only receive the last value provided and ignore the others (which will cause such a bbox query to fail)

**Comment by philvarner** [comment] 2021-07-06 21:42
This appears to be resolved.

**Closed** 2021-07-22 01:51 UTC
